LogFormat: Select Log Format. Supported format are `TEXT` and `JSON`.
LogType: Select Log Type `engine log` and `slow log`.
LogGroup: Specify a CloudWatch Log Group. If the Log Group does not exist, a new Log Group will be created.